# VADs testings

In [1]:
import numpy as np
import torchaudio
import matplotlib.pyplot as plt
from scipy import signal
import os

In [2]:
import os 
import torchaudio

In [3]:
import torch
import torchaudio
import librosa
import numpy as np
import webrtcvad
from scipy.signal import find_peaks

# Опционально: Проверяем доступность SpeechBrain и OpenVINO
try:
    from speechbrain.pretrained import VAD as SpeechBrainVAD
except ImportError:
    print('cant import SpeechBrainVAD')
    SpeechBrainVAD = None

try:
    from openvino.runtime import Core
except ImportError:
    print('cant import openvino')
    Core = None

c:\Users\Bogdan\AppData\Local\Programs\Python\Python311\Lib\inspect.py:992: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  if ismodule(module) and hasattr(module, '__file__'):
C:\Users\Bogdan\AppData\Local\Temp\ipykernel_4896\990377766.py:10: UserWarning: Module 'speechbrain.pretrained' was deprecated, redirecting to 'speechbrain.inference'. Please update your script. This is a change from SpeechBrain 1.0. See: https://github.com/speechbrain/speechbrain/releases/tag/v1.0.0
  from speechbrain.pretrained import VAD as SpeechBrainVAD

# audion prep

In [4]:
audios = [] # (waveform, mask, age)

In [5]:
def plot_waveform_with_mask(waveform, mask, sample_rate=16000):
    plt.figure(figsize=(12, 4))

    # Рисуем волновую форму
    time = range(len(waveform))
    plt.plot(time, waveform, label='Waveform', color='blue')

    # Наносим маску
    plt.plot(time, mask, label='Mask', color='red', alpha=0.5)

    # Оформление графика
    plt.title("Waveform with Mask")
    plt.xlabel("Sample")
    plt.ylabel("Amplitude")
    plt.legend()
    plt.show()

In [6]:
noisy_files = [r'E:\mai\Diploma\speech_enhancement\VAD_testing\noisy_files' +'\\' + i for i in os.listdir(r'E:\mai\Diploma\speech_enhancement\VAD_testing\noisy_files')]
denoised = [r'E:\mai\Diploma\speech_enhancement\VAD_testing\noisy_files_donoised' +'\\' + i for i in os.listdir(r'E:\mai\Diploma\speech_enhancement\VAD_testing\noisy_files_donoised')]
files_paths_for_test = noisy_files + denoised

In [7]:
path = os.path.join("Vino2.wav") # взрослый
waveform, sample_rate = torchaudio.load(path)

waveform
mask = [0]*6500 + [1]*15000 + [0]*3500 + [1]*12000 + [0]*4500 + [1]*11000
mask += [0]*(len(waveform[0]) - len(mask))

for file_path in files_paths_for_test:
    if "Vino2" in file_path:
        for mt in ['100epo', '75epo', '50epo', '25epo']:
            category = 'adult'
            if mt in file_path:
                category = category + '_'+mt
            waveform, sample_rate = torchaudio.load(file_path)
            audios.append((waveform, mask, category))

In [8]:
path = os.path.join("vinograd2.wav") # детский
waveform, sample_rate = torchaudio.load(path)

waveform
mask = [0]*9000 + [1]*12000 + [0]*5000 + [1]*9000 + [0]*4500 + [1]*14000
mask += [0]*(len(waveform[0]) - len(mask))

for file_path in files_paths_for_test:
    if "vinograd2" in file_path:
        for mt in ['100epo', '75epo', '50epo', '25epo']:
            category = 'child'
            if mt in file_path:
                category = category + '_'+mt
            waveform, sample_rate = torchaudio.load(file_path)
            audios.append((waveform, mask, category))

In [9]:


'''path = os.path.join(r"E:\mai\Speech\speech_enhancement\audios\ребенок_4_5.wav") # детский средний
waveform, sample_rate = torchaudio.load(path)

waveform
mask = []
mask += [1]*(len(waveform[0]) - len(mask))

for file_path in files_paths_for_test:
    if "ребенок_4_5" in file_path:
        for mt in ['100epo', '75epo', '50epo', '25epo']:
            category = 'teen'
            if mt in file_path:
                category = category + '_'+mt
            waveform, sample_rate = torchaudio.load(file_path)
            audios.append((waveform, mask, category))'''

'path = os.path.join(r"E:\\mai\\Speech\\speech_enhancement\x07udios\\ребенок_4_5.wav") # детский средний\nwaveform, sample_rate = torchaudio.load(path)\n\nwaveform\nmask = []\nmask += [1]*(len(waveform[0]) - len(mask))\n\nfor file_path in files_paths_for_test:\n    if "ребенок_4_5" in file_path:\n        for mt in [\'100epo\', \'75epo\', \'50epo\', \'25epo\']:\n            category = \'teen\'\n            if mt in file_path:\n                category = category + \'_\'+mt\n            waveform, sample_rate = torchaudio.load(file_path)\n            audios.append((waveform, mask, category))'

In [10]:


path = os.path.join(r"E:\mai\Speech\speech_enhancement\audios\учитель_6.wav")
waveform, sample_rate = torchaudio.load(path)

waveform
mask = [1]*15000 + [0]*2000 + [1]*14000 + [0]*2500+ [1]*7000 
mask += [0]*(len(waveform[0]) - len(mask))

for file_path in files_paths_for_test:
    if "учитель_6" in file_path:
        for mt in ['100epo', '75epo', '50epo', '25epo']:
            category = 'adult'
            if mt in file_path:
                category = category + '_'+mt
            waveform, sample_rate = torchaudio.load(file_path)
            audios.append((waveform, mask, category))

In [11]:


path = os.path.join(r"E:\mai\Speech\speech_enhancement\audios\ребенок_4.wav") # средний 2
waveform, sample_rate = torchaudio.load(path)

waveform
mask = [0]*2000 + [1]*16000 + [0]*2000 + [1]*11000 + [0]*2000 + [1]*2000 + [0]*1000 + [1]*2000 + [0]*9000 + [1]*18000
mask += [0]*(len(waveform[0]) - len(mask))

for file_path in files_paths_for_test:
    if "ребенок_4" in file_path and "ребенок_4_5" not in file_path:
        for mt in ['100epo', '75epo', '50epo', '25epo']:
            category = 'teen'
            if mt in file_path:
                category = category + '_'+mt
            waveform, sample_rate = torchaudio.load(file_path)
            audios.append((waveform, mask, category))

# other

In [12]:

class VADInterface:
    def __init__(self, model_type="webrtc", aggressiveness=3):
        self.model_type = model_type

        if model_type == "webrtc":
            self.vad = webrtcvad.Vad(aggressiveness)
        elif model_type == "silero":
            self.model, _ = torch.hub.load('snakers4/silero-vad', 'silero_vad')
        elif model_type == "torchaudio":
            pass  # Используем torchaudio.functional.vad напрямую
        elif model_type == "librosa":
            pass  # Не требуется загрузка модели
        elif model_type == "speechbrain" and SpeechBrainVAD:
            self.model = SpeechBrainVAD.from_hparams(
                source="speechbrain/vad-crdnn-libriparty", savedir="tmp"
            )
        elif model_type == "openvino" and Core:
            self.core = Core()
            self.model = self.core.read_model("vad_model.xml")  # Укажите путь к вашей модели
            self.compiled_model = self.core.compile_model(self.model, "CPU")
        else:
            raise ValueError(f"Unsupported or unavailable VAD type: {model_type}")

    def apply_vad(self, waveform, sample_rate):
        if self.model_type == "webrtc":
            return self._webrtc_vad(waveform, sample_rate)
        elif self.model_type == "silero":
            return self._silero_vad(waveform, sample_rate)
        elif self.model_type == "torchaudio":
            return torchaudio.functional.vad(waveform, sample_rate, search_time=3)
        elif self.model_type == "librosa":
            return self._librosa_vad(waveform, sample_rate)
        elif self.model_type == "speechbrain":
            return self._speechbrain_vad("audio.wav")  # SpeechBrain работает с файлами
        elif self.model_type == "openvino":
            return self._openvino_vad(waveform)

    def _webrtc_vad(self, waveform, sample_rate):
        frame_size = int(sample_rate * 0.02)  # 20ms frames
        return torch.cat([
            waveform[:, i:i + frame_size]
            for i in range(0, waveform.shape[1], frame_size)
            if self.vad.is_speech(waveform[:, i:i + frame_size].numpy().tobytes(), sample_rate)
        ], dim=1)

    def _silero_vad(self, waveform, sample_rate):
        window = 512

        waveform=waveform[0]
        ub = (len(waveform) // window)*window
        full = []
        for i in range(0, len(waveform[:ub]), window):
            res = self.model(waveform[i:i+window], 16000)
            full += [res.detach().numpy()]*window
        
        speech_probs = np.array(full)[:,0, 0]
        
        mask = speech_probs > 0.5
        return mask
        return waveform[:ub][mask]

    def _librosa_vad(self, waveform, sample_rate):
        '''"""Простая реализация VAD с использованием RMS энергии."""
        energy = librosa.feature.rms(y=waveform.numpy().flatten())
        threshold = np.mean(energy) * 0.5  # Эвристический порог
        mask = energy.flatten() > threshold
        print(mask.shape)
        print(energy.shape)
        peaks, _ = find_peaks(mask)  # Находим интервалы активной речи
        return waveform[:, peaks]'''
        frame_length = 2048 #60504
        hop_length = 512
        # Разделение на фреймы
        def frame_signal(waveform, frame_length, hop_length):
            return waveform.unfold(1, frame_length, hop_length)

        framed_signal = frame_signal(waveform, frame_length, hop_length)
        energies = torch.sum(framed_signal**2, dim=2)

        # Определение активных участков
        energy_threshold = np.median(energies) * 1.3#0.02
        vad_mask = energies > energy_threshold
        return np.repeat(vad_mask, hop_length)
        return vad_mask

    '''def _speechbrain_vad(self, filepath):
        """VAD с использованием SpeechBrain."""
        boundaries = self.model.get_speech_segments(filepath)
        print(f"Speech segments: {boundaries}")
        return boundaries

    def _openvino_vad(self, waveform):
        """VAD с использованием OpenVINO."""
        inputs = {self.model.inputs[0]: waveform.numpy()}
        result = self.compiled_model(inputs)[self.model.outputs[0]]
        mask = result.squeeze() > 0.5  # Бинаризуем результаты
        return waveform[:, mask]'''



def plot_waveforms(original, processed_list, sample_rate, labels):
    """Визуализирует оригинальное и обработанное аудио."""
    plt.figure(figsize=(12, 6))
    time = np.linspace(0, len(original[0]) / sample_rate, len(original[0]))

    plt.plot(time, original[0].numpy(), label="Original", alpha=0.6)
    for processed, label in zip(processed_list, labels):
        plt.plot(time[:len(processed[0])], processed[0].numpy(), label=label, alpha=0.6)

    plt.legend()
    plt.title("VAD Comparison")
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude")
    plt.show()

In [13]:
import numpy as np
import torchaudio
import matplotlib.pyplot as plt
from scipy import signal

def load_audio(filepath):
    """Load audio using torchaudio."""
    waveform, sample_rate = torchaudio.load(filepath)
    return waveform, sample_rate

def add_white_noise(waveform, noise_factor=0.005):
    """Add white noise to the waveform."""
    noise = np.random.normal(0, noise_factor, waveform.shape)
    return waveform + torch.from_numpy(noise).float()

def add_pink_noise(waveform, noise_factor=0.005):
    """Add pink noise to the waveform."""
    n_samples = waveform.shape[1]
    uneven = n_samples % 2
    X = np.random.randn(n_samples // 2 + 1 + uneven) + 1j * np.random.randn(n_samples // 2 + 1 + uneven)
    S = np.sqrt(np.arange(len(X)) + 1.)  # 1/f frequency scaling
    y = (np.fft.irfft(X / S)).real
    pink_noise = np.tile(y[:n_samples], (waveform.shape[0], 1))
    return waveform + noise_factor * torch.from_numpy(pink_noise).float()

def add_brown_noise(waveform, noise_factor=0.005):
    """Add brown noise to the waveform."""
    n = np.cumsum(np.random.randn(waveform.shape[1]))  # Brownian motion
    brown_noise = n / np.max(np.abs(n))  # Normalize
    return waveform + noise_factor * torch.from_numpy(brown_noise).float()

def add_gaussian_noise(waveform, noise_factor=0.005):
    """Add Gaussian noise to the waveform."""
    noise = np.random.normal(0, noise_factor, waveform.shape)
    return waveform + torch.from_numpy(noise).float()

def plot_waveforms(original, noisy, sample_rate, title):
    """Plot original and noisy audio signals."""
    plt.figure(figsize=(12, 4))
    time = np.linspace(0, len(original[0]) / sample_rate, len(original[0]))

    plt.plot(time, original[0].numpy(), label="Original", alpha=0.6)
    plt.plot(time, noisy[0].numpy(), label="Noisy", alpha=0.6)
    plt.legend()
    plt.title(title)
    plt.xlabel("Time (s)")
    plt.ylabel("Amplitude")
    plt.show()

def test_noise():
    # Load an audio file
    original, sample_rate = load_audio("original.wav")

    # Add various types of noise
    noisy_white = add_white_noise(original, noise_factor=0.01)
    noisy_pink = add_pink_noise(original, noise_factor=0.01)
    noisy_brown = add_brown_noise(original, noise_factor=0.01)
    noisy_gaussian = add_gaussian_noise(original, noise_factor=0.01)

    # Plot the results for comparison
    plot_waveforms(original, noisy_white, sample_rate, "White Noise")
    plot_waveforms(original, noisy_pink, sample_rate, "Pink Noise")
    plot_waveforms(original, noisy_brown, sample_rate, "Brown Noise")
    plot_waveforms(original, noisy_gaussian, sample_rate, "Gaussian Noise")

In [14]:
import torch

def iou(pred: torch.Tensor, target: torch.Tensor) -> float:
    """
    Вычисление метрики Intersection over Union (IoU) для одномерных тензоров.
    
    :param pred: предсказания, одномерный тензор
    :param target: целевые значения, одномерный тензор
    :return: значение IoU
    """
    pred = torch.tensor(pred)
    target = torch.tensor(target)
    # Приведение предсказаний к бинарному виду (если нужно)
    pred = (pred > 0.5).float()
    target = (target > 0.5).float()

    # Вычисление пересечения и объединения
    intersection = torch.sum(pred * target)
    union = torch.sum(pred) + torch.sum(target) - intersection

    # Избегаем деления на 0
    iou_value = intersection / union if union != 0 else torch.tensor(0.0)

    return iou_value.item()


def dice(pred: torch.Tensor, target: torch.Tensor) -> float:
    """
    Вычисление Dice коэффициента для одномерных тензоров.
    
    :param pred: предсказания, одномерный тензор
    :param target: целевые значения, одномерный тензор
    :return: значение Dice
    """
    pred = torch.tensor(pred)
    target = torch.tensor(target)
    # Приведение предсказаний к бинарному виду (если нужно)
    pred = (pred > 0.5).float()
    target = (target > 0.5).float()

    # Вычисление пересечения
    intersection = torch.sum(pred * target)
    # Вычисление Dice коэффициента
    dice_value = (2 * intersection) / (torch.sum(pred) + torch.sum(target))

    return dice_value.item()

def accuracy(pred: torch.Tensor, target: torch.Tensor) -> float:
    """
    Вычисление Accuracy для бинарных одномерных тензоров.

    :param pred: предсказания, одномерный тензор
    :param target: целевые значения, одномерный тензор
    :return: значение Accuracy
    """
    pred = torch.tensor(pred)
    target = torch.tensor(target)
    pred = (pred > 0.5).float()
    target = (target > 0.5).float()

    correct = torch.sum(pred == target)
    total = target.numel()

    return (correct / total).item()

def precision(pred: torch.Tensor, target: torch.Tensor) -> float: 
    """
    Вычисление Precision для бинарных одномерных тензоров.

    :param pred: предсказания, одномерный тензор
    :param target: целевые значения, одномерный тензор
    :return: значение Precision
    """
    pred = torch.tensor(pred)
    target = torch.tensor(target)
    pred = (pred > 0.5).float()
    target = (target > 0.5).float()

    tp = torch.sum((pred == 1) & (target == 1)).float()
    fp = torch.sum((pred == 1) & (target == 0)).float()

    if tp + fp == 0:
        return 0.0

    return (tp / (tp + fp)).item()

def recall(pred: torch.Tensor, target: torch.Tensor) -> float:
    """
    Вычисление Recall для бинарных одномерных тензоров.

    :param pred: предсказания, одномерный тензор
    :param target: целевые значения, одномерный тензор
    :return: значение Recall
    """
    pred = torch.tensor(pred)
    target = torch.tensor(target)
    pred = (pred > 0.5).float()
    target = (target > 0.5).float()

    tp = torch.sum((pred == 1) & (target == 1)).float()
    fn = torch.sum((pred == 0) & (target == 1)).float()

    if tp + fn == 0:
        return 0.0

    return (tp / (tp + fn)).item()

In [15]:
def apply_webrtc(waveform, sample_rate=16000):
    if sample_rate != 16000:
        waveform = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=16000)(waveform)
        sample_rate = 16000

    # Преобразуем в моно (если аудиофайл стерео)
    if waveform.shape[0] > 1:
        waveform = waveform.mean(dim=0)

    # Преобразуем тензор в PCM-байты
    audio_bytes = (waveform.numpy().flatten() * 32767).astype("int16").tobytes()

    vad = webrtcvad.Vad(2)  # 2 – средняя агрессивность

    frame_duration = 30 
    frame_size = int(sample_rate * frame_duration / 1000) * 2
    num_frames = len(audio_bytes) // frame_size

    speech_mask = np.zeros(num_frames, dtype=np.int32)

    for i in range(num_frames):
        frame = audio_bytes[i * frame_size: (i + 1) * frame_size]
        if vad.is_speech(frame, sample_rate):
            speech_mask[i] = 1

    return torch.from_numpy(speech_mask).repeat_interleave(int(sample_rate * frame_duration / 1000))

In [16]:
vad_silero = VADInterface(model_type="silero")
vad_librosa = VADInterface(model_type="librosa")

Using cache found in C:\Users\Bogdan/.cache\torch\hub\snakers4_silero-vad_master

In [17]:
processed_list = []
sample_rate = 48_000

for waveform, mask, age in audios:
    processed_list.append(('silero', vad_silero.apply_vad(waveform, sample_rate), mask, age))
    processed_list.append(('webrtc', apply_webrtc(waveform, sample_rate), mask, age))
    processed_list.append(('librosa', vad_librosa.apply_vad(waveform, sample_rate), mask, age))

In [18]:
results = []

for vad_name, pred_mask, gt_mask, age in processed_list:
    iou_value = iou(pred_mask, gt_mask[:len(pred_mask)])
    dice_value = dice(pred_mask, gt_mask[:len(pred_mask)])
    
    acc_value = accuracy(pred_mask, gt_mask[:len(pred_mask)]) #accuracy precision recall
    prec_value = precision(pred_mask, gt_mask[:len(pred_mask)])
    recall_value = recall(pred_mask, gt_mask[:len(pred_mask)])
    f1_value = 2*(recall_value * prec_value)/(recall_value + prec_value) if (recall_value + prec_value) != 0 else 0
    
    results.append((vad_name, age, iou_value, dice_value, acc_value, prec_value, recall_value, f1_value))

C:\Users\Bogdan\AppData\Local\Temp\ipykernel_4896\968437393.py:11: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pred = torch.tensor(pred)
C:\Users\Bogdan\AppData\Local\Temp\ipykernel_4896\968437393.py:35: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pred = torch.tensor(pred)
C:\Users\Bogdan\AppData\Local\Temp\ipykernel_4896\968437393.py:56: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pred = torch.tensor(pred)
C:\Users\Bogdan\AppData\Local\Temp\ipykernel_4896\968437393.py:74: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pred = torch.tensor(pred)
C:\Users\Bogdan\AppData\Local\Temp\ipykernel_4896\968437393.py:95: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  pred = torch.tensor(pred)

In [19]:
import pandas as pd
df = pd.DataFrame(results, columns=['vad_name', 'age', 'iou_value', 'dice_value', 'accuracy', 'precision', 'recall', 'f1'])

In [20]:
df

,vad_name,age,iou_value,dice_value,accuracy,precision,recall,f1
0,silero,adult,0.638248,0.779184,0.734244,0.808650,0.751789,0.779184
1,webrtc,adult,0.303862,0.466095,0.320437,0.498333,0.437775,0.466095
2,librosa,adult,0.658150,0.793836,0.779230,0.986094,0.664316,0.793836
3,silero,adult,0.683123,0.811733,0.762342,0.802220,0.821474,0.811733
4,webrtc,adult,0.303862,0.466095,0.320437,0.498333,0.437775,0.466095
...,...,...,...,...,...,...,...,...
955,webrtc,teen,0.793333,0.884758,0.801282,0.862319,0.908397,0.884758
956,librosa,teen,0.610922,0.758475,0.727105,0.920942,0.644735,0.758475
957,silero,teen,0.856718,0.922830,0.892538,0.866542,0.986939,0.922830
958,webrtc,teen,0.793333,0.884758,0.801282,0.862319,0.908397,0.884758
959,librosa,teen,0.610922,0.758475,0.727105,0.920942,0.644735,0.758475

In [21]:
df.groupby(["vad_name", "age"])[['accuracy', 'precision', 'recall', 'f1']].mean().reset_index()

   vad_name           age  accuracy  precision    recall        f1
0   librosa         adult  0.601084   0.826845  0.521457  0.637925
1   librosa  adult_100epo  0.587961   0.807191  0.508344  0.622704
2   librosa   adult_25epo  0.581259   0.806233  0.500817  0.617161
3   librosa   adult_50epo  0.574472   0.795667  0.501820  0.614505
4   librosa   adult_75epo  0.565486   0.785131  0.497316  0.607737
5   librosa         child  0.627157   0.751396  0.557700  0.639842
6   librosa  child_100epo  0.629891   0.756554  0.556229  0.640691
7   librosa   child_25epo  0.649457   0.777882  0.574514  0.660372
8   librosa   child_50epo  0.645109   0.778569  0.563543  0.653650
9   librosa   child_75epo  0.627717   0.752319  0.556229  0.639083
10  librosa          teen  0.675205   0.886157  0.586750  0.705173
11  librosa   teen_100epo  0.699002   0.902209  0.613143  0.729857
12  librosa    teen_25epo  0.686957   0.883819  0.609306  0.720615
13  librosa    teen_50epo  0.675293   0.886600  0.586163  0.704948
14  librosa    teen_75epo  0.693848   0.899808  0.607959  0.724490
15   silero         adult  0.500476   0.813809  0.266306  0.329774
16   silero  adult_100epo  0.488300   0.857873  0.245795  0.310336
17   silero   adult_25epo  0.513338   0.977056  0.282721  0.356284
18   silero   adult_50epo  0.541768   0.858996  0.317692  0.398871
19   silero   adult_75epo  0.560796   0.972512  0.358043  0.414347
20   silero         child  0.441166   0.056479  0.049679  0.049430
21   silero  child_100epo  0.420683   0.000000  0.000000  0.000000
22   silero   child_25epo  0.420683   0.000000  0.000000  0.000000
23   silero   child_50epo  0.420683   0.000000  0.000000  0.000000
24   silero   child_75epo  0.420683   0.000000  0.000000  0.000000
25   silero          teen  0.679877   0.786965  0.601166  0.627416
26   silero   teen_100epo  0.703656   0.926648  0.610694  0.644172
27   silero    teen_25epo  0.608631   0.694879  0.443673  0.506615
28   silero    teen_50epo  0.655453   0.939184  0.534490  0.569641
29   silero    teen_75epo  0.664807   0.869962  0.575633  0.609915
30   webrtc         adult  0.509865   0.745579  0.518670  0.596523
31   webrtc  adult_100epo  0.490575   0.765053  0.483748  0.585587
32   webrtc   adult_25epo  0.454514   0.725327  0.429419  0.534156
33   webrtc   adult_50epo  0.478323   0.757526  0.460165  0.565256
34   webrtc   adult_75epo  0.415575   0.743761  0.393394  0.506702
35   webrtc         child  0.532552   0.545839  0.919187  0.684759
36   webrtc  child_100epo  0.526786   0.543269  0.911290  0.680723
37   webrtc   child_25epo  0.565476   0.562402  0.967742  0.711226
38   webrtc   child_50epo  0.556548   0.558941  0.943548  0.701780
39   webrtc   child_75epo  0.544643   0.551664  0.943548  0.696181
40   webrtc          teen  0.637220   0.812721  0.728590  0.760207
41   webrtc   teen_100epo  0.626603   0.827132  0.695611  0.746791
42   webrtc    teen_25epo  0.605769   0.803297  0.691794  0.738755
43   webrtc    teen_50epo  0.586538   0.789567  0.668893  0.716205
44   webrtc    teen_75epo  0.633013   0.827986  0.702290  0.747515

In [22]:
print(
        df.pivot_table(
            index="vad_name", columns="age", values="accuracy", aggfunc="mean"
        )[[ 'adult', 'adult_25epo', 'adult_50epo', 'adult_75epo', 'adult_100epo',
            'teen', 'teen_25epo', 'teen_50epo', 'teen_75epo', 'teen_100epo',
            'child', 'child_25epo', 'child_50epo', 'child_75epo', 'child_100epo']]
    )

age          adult  adult_25epo  adult_50epo  adult_75epo  adult_100epo  \
vad_name
librosa   0.601084     0.581259     0.574472     0.565486      0.587961
silero    0.500476     0.513338     0.541768     0.560796      0.488300
webrtc    0.509865     0.454514     0.478323     0.415575      0.490575

age           teen  teen_25epo  teen_50epo  teen_75epo  teen_100epo     child  \
vad_name
librosa   0.675205    0.686957    0.675293    0.693848     0.699002  0.627157
silero    0.679877    0.608631    0.655453    0.664807     0.703656  0.441166
webrtc    0.637220    0.605769    0.586538    0.633013     0.626603  0.532552

age       child_25epo  child_50epo  child_75epo  child_100epo
vad_name
librosa      0.649457     0.645109     0.627717      0.629891
silero       0.420683     0.420683     0.420683      0.420683
webrtc       0.565476     0.556548     0.544643      0.526786

In [23]:

print(
        df.pivot_table(
            index="vad_name", columns="age", values="recall", aggfunc="mean"
        )[[ 'adult', 'adult_25epo', 'adult_50epo', 'adult_75epo', 'adult_100epo',
            'teen', 'teen_25epo', 'teen_50epo', 'teen_75epo', 'teen_100epo',
            'child', 'child_25epo', 'child_50epo', 'child_75epo', 'child_100epo']]
    )

age          adult  adult_25epo  adult_50epo  adult_75epo  adult_100epo  \
vad_name
librosa   0.521457     0.500817     0.501820     0.497316      0.508344
silero    0.266306     0.282721     0.317692     0.358043      0.245795
webrtc    0.518670     0.429419     0.460165     0.393394      0.483748

age           teen  teen_25epo  teen_50epo  teen_75epo  teen_100epo     child  \
vad_name
librosa   0.586750    0.609306    0.586163    0.607959     0.613143  0.557700
silero    0.601166    0.443673    0.534490    0.575633     0.610694  0.049679
webrtc    0.728590    0.691794    0.668893    0.702290     0.695611  0.919187

age       child_25epo  child_50epo  child_75epo  child_100epo
vad_name
librosa      0.574514     0.563543     0.556229      0.556229
silero       0.000000     0.000000     0.000000      0.000000
webrtc       0.967742     0.943548     0.943548      0.911290

In [24]:

print(
        df.pivot_table(
            index="vad_name", columns="age", values="precision", aggfunc="mean"
        )[[ 'adult', 'adult_25epo', 'adult_50epo', 'adult_75epo', 'adult_100epo',
            'teen', 'teen_25epo', 'teen_50epo', 'teen_75epo', 'teen_100epo',
            'child', 'child_25epo', 'child_50epo', 'child_75epo', 'child_100epo']]
    )

age          adult  adult_25epo  adult_50epo  adult_75epo  adult_100epo  \
vad_name
librosa   0.826845     0.806233     0.795667     0.785131      0.807191
silero    0.813809     0.977056     0.858996     0.972512      0.857873
webrtc    0.745579     0.725327     0.757526     0.743761      0.765053

age           teen  teen_25epo  teen_50epo  teen_75epo  teen_100epo     child  \
vad_name
librosa   0.886157    0.883819    0.886600    0.899808     0.902209  0.751396
silero    0.786965    0.694879    0.939184    0.869962     0.926648  0.056479
webrtc    0.812721    0.803297    0.789567    0.827986     0.827132  0.545839

age       child_25epo  child_50epo  child_75epo  child_100epo
vad_name
librosa      0.777882     0.778569     0.752319      0.756554
silero       0.000000     0.000000     0.000000      0.000000
webrtc       0.562402     0.558941     0.551664      0.543269

In [25]:
print(
        df.pivot_table(
            index="vad_name", columns="age", values="dice_value", aggfunc="mean"
        )[[ 'adult', 'adult_25epo', 'adult_50epo', 'adult_75epo', 'adult_100epo',
            'teen', 'teen_25epo', 'teen_50epo', 'teen_75epo', 'teen_100epo',
            'child', 'child_25epo', 'child_50epo', 'child_75epo', 'child_100epo']]
    )

age          adult  adult_25epo  adult_50epo  adult_75epo  adult_100epo  \
vad_name
librosa   0.637925     0.617161     0.614505     0.607737      0.622704
silero    0.329774     0.356284     0.398871     0.414347      0.310336
webrtc    0.596523     0.534156     0.565256     0.506702      0.585587

age           teen  teen_25epo  teen_50epo  teen_75epo  teen_100epo     child  \
vad_name
librosa   0.705173    0.720615    0.704948    0.724490     0.729857  0.639842
silero    0.627416    0.506615    0.569641    0.609915     0.644172  0.049430
webrtc    0.760207    0.738755    0.716205    0.747515     0.746791  0.684759

age       child_25epo  child_50epo  child_75epo  child_100epo
vad_name
librosa      0.660372      0.65365     0.639083      0.640691
silero       0.000000      0.00000     0.000000      0.000000
webrtc       0.711226      0.70178     0.696181      0.680723

In [26]:

print(
        df.pivot_table(
            index="vad_name", columns="age", values="f1", aggfunc="mean"
        )[[ 'adult', 'adult_25epo', 'adult_50epo', 'adult_75epo', 'adult_100epo',
            'teen', 'teen_25epo', 'teen_50epo', 'teen_75epo', 'teen_100epo',
            'child', 'child_25epo', 'child_50epo', 'child_75epo', 'child_100epo']]
    )

age          adult  adult_25epo  adult_50epo  adult_75epo  adult_100epo  \
vad_name
librosa   0.637925     0.617161     0.614505     0.607737      0.622704
silero    0.329774     0.356284     0.398871     0.414347      0.310336
webrtc    0.596523     0.534156     0.565256     0.506702      0.585587

age           teen  teen_25epo  teen_50epo  teen_75epo  teen_100epo     child  \
vad_name
librosa   0.705173    0.720615    0.704948    0.724490     0.729857  0.639842
silero    0.627416    0.506615    0.569641    0.609915     0.644172  0.049430
webrtc    0.760207    0.738755    0.716205    0.747515     0.746791  0.684759

age       child_25epo  child_50epo  child_75epo  child_100epo
vad_name
librosa      0.660372      0.65365     0.639083      0.640691
silero       0.000000      0.00000     0.000000      0.000000
webrtc       0.711226      0.70178     0.696181      0.680723